timeout 3 sudo python userdata/api/getGps.py